# Tarefas especÃ­ficas do CentOS
- name: Garantindo o epel-release em CentOS
  package:
    name: epel-release
    state: present
- name: Desabilitando o SELinux em CentOS
  selinux:
    state: disabled
