version: '3'

services:
  rocketchat:
    image: rocketchat/rocket.chat:1.3.2
    restart: unless-stopped
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
    depends_on:
      - mongo
    labels:
      - "traefik.backend=rocketchat"
      - "traefik.frontend.rule=Host: chat.4labs.example"

  mongo:
    image: mongo:4.0
    restart: unless-stopped
    volumes:
     - $PWD/db:/data/db
    command: mongod --smallfiles --oplogSize 128 --replSet rs0 --storageEngine=mmapv1
    labels:
      - "traefik.enable=false"

  mongo-init-replica:
    image: mongo:4.0
    command: >
      bash -c
        "for i in `seq 1 30`; do
          mongo mongo/rocketchat --eval \"
            rs.initiate({
              _id: 'rs0',
              members: [ { _id: 0, host: 'localhost:27017' } ]})\" &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    depends_on:
      - mongo

  hubot:
    image: rocketchat/hubot-rocketchat:latest
    hostname: hubot
    restart: unless-stopped
    extra_hosts:
      - "automation.4labs.example:10.5.25.10"
    environment:
      - ROCKETCHAT_URL=rocketchat:3000
      - ROCKETCHAT_ROOM=general
      - ROCKETCHAT_USER=cybertux
      - ROCKETCHAT_PASSWORD=devops@4linux
      - ROCKETCHAT_AUTH=password
      - BOT_NAME=chatops
      - LISTEN_ON_ALL_PUBLIC=true
      - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-diagnostics,hubot-rundeck
    depends_on:
      - rocketchat
    labels:
      - "traefik.enable=false"


  traefik:
   image: traefik:1.7.18
   restart: unless-stopped
   command: traefik /
     --docker /
     --api /
     --docker.domain=4labs.example /
     --entrypoints="Name:http Address::80"  /
     --entryPoints="Name:https Address::443" /
     --defaultentrypoints="http,https"
   ports:
     - 80:80
     - 443:443
     - 8080:8080
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
